In [143]:
import neattext as nt
import re
import pandas as pd

In [172]:
def preprocess_text(text):
    text = re.sub(r'[^\u0400-\u04FF\s.,;?!]', '', text)

    docx = nt.TextFrame(text)
    docx.remove_puncts()
    docx.remove_emojis()
    docx.remove_phone_numbers()
    docx.remove_numbers()
    docx.remove_emails()
    docx.remove_stopwords(lang='ru')
    docx.normalize(level='deep')

    text = docx.text.strip()

    return text

def preprocess_file(filepath):
    processed_lines = []
    ignore_patterns = re.compile(r'украи|росс|росси|украин', re.IGNORECASE)
    
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            if not ignore_patterns.search(line):  # Проверяем, не содержит ли строка запрещенные паттерны
                processed_line = preprocess_text(line)
                if processed_line:  # Проверяем, не пустая ли строка
                    processed_lines.append(processed_line)
                
    return processed_lines

In [173]:

filepath = './data/noisy_text/misha_noisy_text.txt'

processed_lines = preprocess_file(filepath)
for line in processed_lines:
    print(line)
print(len(processed_lines))

зато гослинг дал почесать пузо счастлив
там вторая кошка большая удалось потрогать жаль очень жаль
короче некому михаилу день рождения ходил там кот райан гослинг
второй половине года ушёл ни разу пожалел хотя рекомендательная система послабее зато музыки ютуб
почему дунул волк крышу снесло поросятам
ответ х метровые снежные фаллосы студентов екатеринбургского уральского федерального университета студенты итмо подготовили снежный перформанс напротив главного корпуса
добиться дисквалификации пять секунд
покривлялсяпозвездился выезде университетский лагерь понравилось выиграли конкурсе костюмов хеллоуин фотки потом тут вспомнил сколько обещал выложить выложилвсего ровно столько сколько требовалось телу мозгу душе
кот думает тапок тапком каким открыт предложениям
ваш друг месяц пропадает материального мира потом предлагает вскипятиться вероятно правильно сделали жизни
балконе лютая туса даже позвали
сегодня подарили пирожное
давно щитпоста возобновляем
выросли ебанутые огурцы
всегда низкие цены магазине галактика унитазоввяземский переулок этаж
пара видосов записанных день июлякогданибудь обязательно наложу музыку выложу сюда
ну чё школота закончилось лето
коты лично радуга лично
блин блинский шеи родаков слазить
отличие инсталляции перформансаинсталляция насрал комуто под дверь позвонил звонок убежал потом человек открывает дверь видит насраноа перформанс сначала звонишь звонок человек открывает дверь начинаешь срать
картинка древняя мегалокальная должна здесь
друзья расскажите сегодняшняя погода
щитпост довольно классический немного текстовый
сегодня подарили шоколадку теперь очень приятно
оцените снеговика лепил
кото правильнокотощитпост
всегда называет детьми
бля этоя отказываюсь комментировать
иногда слова ранить огнестрельное оружие
люди котика деле считают жизнь ужасной шутки несмешные
заебал котами надеюсь иначе канал можно закрывать
киньте вашей красивой фотке осени
потеряться похуй куда идти
смотрит любимых подпищиков
еженедельный щитпост переносится сюда
35

In [174]:
import os

directory_path = '.\data\noisy_text'

# Перебираем все файлы в директории
for filename in os.listdir(directory_path):
    filepath = os.path.join(directory_path, filename)

    # Проверяем, является ли объект по указанному пути файлом
    if os.path.isfile(filepath):
        print(filepath)

.\data\noisy_text\aufitmem_noisy_text.txt
.\data\noisy_text\faggod_noisy_text.txt
.\data\noisy_text\field_noisy_text.txt
.\data\noisy_text\inquisition_noisy_text.txt
.\data\noisy_text\madyson_noisy_text.txt
.\data\noisy_text\misha_noisy_text.txt
.\data\noisy_text\mudrost_noisy_text.txt

In [181]:
import os

directory_path = '.\data\noisy_text'

all_noisy_text_line = []
for filename in os.listdir(directory_path):
    filepath = os.path.join(directory_path, filename)

    # Проверяем, является ли объект по указанному пути файлом
    if os.path.isfile(filepath):
        print(filepath)
        processed_lines = preprocess_file(filepath)
        all_noisy_text_line += processed_lines

.\data\noisy_text\aufitmem_noisy_text.txt
.\data\noisy_text\faggod_noisy_text.txt
.\data\noisy_text\field_noisy_text.txt
.\data\noisy_text\inquisition_noisy_text.txt
.\data\noisy_text\madyson_noisy_text.txt
.\data\noisy_text\misha_noisy_text.txt
.\data\noisy_text\mudrost_noisy_text.txt

In [182]:
noisy_text_df = pd.DataFrame(all_noisy_text_line, columns=['text'])

noisy_text_df['is_noisy_text'] = True

noisy_text_df

                                                   text  is_noisy_text
0                             десять тысяч ёбаных галош         True
1                 таска войдёт анналы истории два вошла         True
2     графика би лайкладно мужикиприходимуверенно еб...         True
3                                   аж укачало немножко         True
4                                 насос ванной съебался         True
...                                                 ...          ...
5385  сколько должен зарабатывать мужчинав лет рубле...         True
5386  душе пою исключительно военные марши гимныпою ...         True
5387  странно писать каналнапишешь мудрость молчание...         True
5388  сразу приватная мудрость опубликована пабликеб...         True
5389  забудьте про ботая создал канал сидите мобильн...         True

[5390 rows x 2 columns]

In [183]:
noisy_text_df.to_csv('./data/noisy_text_df.csv', index=False)

In [184]:
filtered_df = noisy_text_df.loc[noisy_text_df['text'].str.len() >= 30]
filtered_df

                                                   text  is_noisy_text
1                 таска войдёт анналы истории два вошла         True
2     графика би лайкладно мужикиприходимуверенно еб...         True
5                 тааак титов дани даниил райан гослинг         True
7     залить лабу нужна веткаветку дамчтобы смерджит...         True
8                     футболку задрал почесался событие         True
...                                                 ...          ...
5385  сколько должен зарабатывать мужчинав лет рубле...         True
5386  душе пою исключительно военные марши гимныпою ...         True
5387  странно писать каналнапишешь мудрость молчание...         True
5388  сразу приватная мудрость опубликована пабликеб...         True
5389  забудьте про ботая создал канал сидите мобильн...         True

[4409 rows x 2 columns]

In [185]:
filtered_df.to_csv('./data/filtered_noisy_text_df.csv', index=False)