In [17]:
import neattext as nt
import re
import pandas as pd

In [28]:
def preprocess_text(text):
    text = re.sub(r'[^\u0400-\u04FF\s.,;?!]', '', text)
    
    docx = nt.TextFrame(text)
    docx.remove_puncts()
    docx.remove_emojis()
    docx.remove_phone_numbers()
    docx.remove_numbers()
    docx.remove_emails()
    docx.remove_stopwords(lang='ru')
    docx.normalize(level='deep')

    text = docx.text.strip()

    return text

def preprocess_file(filepath):
    
    processed_lines = []
    
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            processed_line = preprocess_text(line)
            if processed_line:  # Проверяем, не пустая ли строка
                processed_lines.append(processed_line)
                
    return processed_lines

In [29]:

filepath = './data/wiki/random_pages10.txt'

processed_lines = preprocess_file(filepath)
for line in processed_lines:
    print(line)

Торремолинос исп город муниципалитет Испании входит провинцию Малага составе автономного сообщества Андалусия Муниципалитет находится составе района комарки КостадельСольОксиденталь
Занимает площадь км Население тыс человек год
Расстояние административного центра провинции км
Пляжный курорт средиземноморском побережье Испании КостадельСоль
Рогатица босн серб Рогатица хорв город восточной части Республики Сербской составе Боснии Герцеговины Центр одноимённой общины регионе ИсточноСараево
Расположен километрах северовосток Сараево полпути дороге ГораджеСоколац
Численность населения города переписи года составляет человек общины человека
Этнический состав населения города Рогатица переписи года
Код объекта государственном водном реестре
Библиотека СенСюльпис историческое здание расположенное улице СенДени фр рус Монреале Квебеке Канада объявлено Историческим памятником Квебека году
Библиотека СенСюльпис спроектированная архитектором Эдженом Пайеттом фр рус считается лучших образцов архитектуры бозар провинции Квебек Построенное между годами году здание открылось частная библиотека Общества Сульпициан
первая библиотека французском языке Канаде
апреля года объявлен архитектурный конкурс Представлено одиннадцать предложений предложение архитектора Эджена Пайетта фр рус выигрывается конкурсе здание стиле бозар спроектировано году Эдженом Пайеттом фр рус также спроектировал центральную библиотеку Монреаля Дом ГастонМирон фр рус просьбе Общества Сульпициане использования университетскими исследователями студентами широкой публикой Первыми библиотекаря Эгидиус Фотё фр рус Оливье Мораулт фр рус
году просьбе Эгидиуса Фотё фр рус Гвидо Нинчери создал экслибрис библиотеки Экслибрис представляет две башни единственные остатки форта построенного сульпицианцами веке Также обозначены две важные даты первая год соответствует открытию Семинарии НотрДам год дате открытия библиотеки СенСюльпис
время библиотека настоящей публичной библиотекой хотя очень популярна среди горожан скорее частная исследовательская библиотека университетского типа доступная общественности часто посещали многие интеллектуалы времени Куратор Эгидиус Фотё фр рус занимался формированием коллекции высокого уровня отправился США Европу совершить массовые покупки Также устанавливает местную политику закупок Создается служба тиража книг изначально планировалось период книговыдача продолжает расти Оборот бюджета библиотеки фунтов период годов годы Большом зале расположенном подвале устраивались разнообразные культурные мероприятия
года начались финансовые проблемы Общество Сульпициане управляющие заведением понесли огромные убытки фондовом рынке поэтому сокращают персонал закупки книг
года библиотека перестала выдавать книги
году Национальная консерватория музыки занимавшая помещение библиотеки года сделала предложение покупке Многие общественные деятели времени выступили против сделки конечном итоге состоялась Кризис года больше ухудшил финансовое положение Сульпициане другого выхода закрыть июля года
Библиотека приобретена году правительством Квебека эквивалентно неуплаченным налогам Общество Сульпициане городу Монреаль
Библиотека вновь откроет двери января года дополнение коллекции СенСюльпис добавлены другие документы составляющие национальную коллекцию После робкого старта библиотека СенСюльпис снова стала популярной Несмотря успех нормальному функционированию препятствует ряд проблем частности отсутствие профессиональных библиотекарей нехватка помещений персонала Куратор Дэмиен Жасмин неоднократно высказывающийся проблемах учреждения ушел отставку году
отставка заставила штат Квебек осознать важность библиотеки Поэтому штат приступает найму квалифицированного персонала ремонту здания году Жорж Картье первый профессиональный библиотекарь стал куратором году библиотека стала Национальной библиотекой Квебека Здание июля внесено список исторических памятников Культурного наследия Квебека
Проект Великая библиотека Квебека предполагает перенос национальной коллекции новое здание бульваре Мезоннёв Пустое здание улице СенДени продано году млн Монреальскому университету Квебека выставил продажу два года спустя Противодействие частной передаче исторического здания привело правительство Квебека выкупило здание миллиона долларов году Правительство начало поиск партнеров использования
году Университет Квебека Монреале купил здание вынужден продать обратно министерству культуры финансовым причинам году году объявлено планах превратить здание музыкальный центр разместится группа музыкальных групп Квебека представил первый сезон концертов сентября май года году объявлено здание использоваться новый технологический инкубатор библиотека подростков
января года Министерство культуры коммуникаций Квебека города Монреаля объявили Национальная библиотека архивы Квебека иметь полномочия возродить библиотеку СенСюльпис случае библиотека должна стать лабораторией инноваций также библиотекой подростков июня года объявлено консорциум выиграл архитектурный конкурс модернизацию восстановление здания здание носит название находится ведении руководства библиотеки Открытие библиотеки впервые объявленное год отложено весны года затем перенесено год позже задержка вызвана слишком высокой стоимостью реконструкции Библиотекарь Бенуа Миньо директор отвечающий проект
Франция
Габсбургская монархия
Жан Виктор Моро
Эрцгерцог Карл
Битва Канштадте бои Канштадте Эсслингене происходила июля года между французской РейнскоМозельской армией генерала Жана Моро австрийской ВерхнеРейнской армией эрцгерцога Карла окрестностях города Штутгарта кампанию года время войны Первой коалиции Битва Канштадте небольшой французской победой вынудила эрцгерцога Карла оставить позиции Неккаре продолжить отступление Дунаю
конце июня французская армия под командованием генерала Моро переправилась через Рейн Страсбурге одержала ряд побед над австрийской ВерхнеРейнской армией сначала под фельдмаршалом Латуром затем Эттлингене июля года над эрцгерцогом Карлом
После поражения Эттлингене эрцгерцог Карл решил боем отступить Дунаю где хотел присоединится отступившей севера армии Вартенслебена затем повернуть двух французских армий окажется наиболее уязвимой
июля эрцгерцог достиг Неккара Людвигсбурге восьми милях северу Штутгарта Затем переправился через реку занял прочную оборонительную позицию восточном берегу Между Оттмарсхаймом Мюндельхаймом стал летающий корпус батальона эскадронов Большая часть армии саксонских войск вместе батальонов эскадронов расположилась лагерем правом берегу Неккара Канштадтом двух милях северовостоку Штутгарта Правый фланг высотах РемсекенаНеккаре левый протянулся вдоль реки Эсслингена Другой летающий корпус батальонов эскадронов прикрыл левое крыло расположившись Плохингене Австрийский авангард батальонов эскадронов размещен западном берегу реки
июля после Эттлингена французы начали преследовать австрийцев направлении Лангенштейнбаха силами корпуса Дезе правом фланге французской армии корпус Ферино июля Эльце оттеснил корпус Конде австрийцев Фрёлиха июля генерал СенСир дивизией Тапонье батальонов эскадронов занял Штутгарт дивизия Дюэма батальона эскадронов стала впереди Хорба Попытка овладеть переправой Канштадте окончилась неудачей июля две дивизии левого крыла французской РейнскоМозельской армии под командованием генерала Дезе резервный корпус батальонов эскадронов прибыли Файхинген
Положение австрийцев Канштадте Эсслингене слишком опасным Моро ибо продолжить операции оттеснив Неккара Моро решил атаковать австрийскую позицию понимал лобовая атака слишком дорогостоящей поэтому решил попытаться обойти австрийский левый фланг приказал генералу СенСиру атаковать австрийскую линию Канштадта Эсслингена
Эрцгерцог разгадал план противника вечером июля стал перебрасывать войска батальонов эскадронов угрожаемые участки подкрепления прибыли районы вовремя раз тогда рассвета дивизия Тапонье двинулась против Канштадта дивизия генерала Лароша против Эсслингена
Тапонье атаковал деревню Берг авангард расположенный перед Канштадтом Австрийцы отброшены назад реку захвачены пригороды Канштадта Правда сломать мост через Неккар австрийцам удалось поскольку контролировали город правый берег обстоятельство использовано французами конце концов бой участке прекращался ночи ограничился довольно сильной перестрелкой берега реки против другого
время Ларош атаковал отряд фельдмаршаллейтенанта Готце близ Эсслингена Наступая колонной дороге ведущей Дегерлоха Неллинген через Руит направлении Эсслингена Вейлерхофа отбросил австрийских гвардейцев сады Эсслингена высоту перед таможней Готце контратаковал двумя батальонами тремя егерскими ротами выгнал французов соседнего леса заняли Вейлерхоф Французы получили подкрепления повторили атаку однако отбита третья наступила ночь австрийцы остались владеть Вейлерхофом холмами пределами Эсслингена Французы со стороны заняли позиции Руита выставили пикеты опушке леса впереди
позициях обе стороны оставались день июля Эрцгерцог ждал повторения атак противника последовала поэтому вечером отдал приказ начать отступление Швабский саксонский корпуса покинули союзника ушли Гамердинген другие сторону Нюрнберга июля части СенСира переправились через Неккар заняли Эсслинген Канштадт
СантуАнтониудасМисойнс порт муниципалитет Бразилии входит штат РиуГрандидуСул Составная часть мезорегиона Северозапад штата РиуГрандидуСул Входит экономикостатистический микрорегион СантуАнжелу Население составляет человек год Занимает площадь км Плотность населения челкм
Город основан октября года
Климат местности субтропический гумидный соответствии классификацией Кёппена климат относится категории
Владимирские губернские ведомости рус дореф Владимірскія губернскія вѣдомости первое периодическое печатное издание официальная газета Владимирской губернии
Первый номер газеты вышел января года
другие Губернские ведомости газета состояла официальной неофициальной частей Положении порядке дел Губернских Правлениях июня года отмечалось следующее облегчения сокращения порядке сношений Губернского Правления доставления присутственным местам должностным лицам вообще каждому удобнейшего средства получать надлежащее время сведения постановлениях распоряжениях Губернского Начальства равно других предметах следующих общему сведению издаются каждом Губернском Правлении особые Губернские Ведомости Губернские Ведомости разделяются две части оффициальную оффициальную положения перечислены темы следовало рассматривать официальной части речь шла предметах неофициальной части первой под названием Часть Оффиціальная публиковались правительственные губернские информационные законодательнораспорядительные материалы Вторая часть называлась Прибавление къ Владимірскимъ Губернскимъ Ведомостямъ посвящена различным новостным заметкам событиях жизни губернии также значительное место уделялось краеведению также здесь публиковались исторические географические статистические материалы время газете запрещалось печатать какиелибо материалы политические темы
Первым главным редактором неофициальной части стал производитель дел статистического комитета З Богословский занимался размещением газете работ членов комитета включая заметки различных интересных событиях произошли последнее время губернии
января год главным редактором неофициальной части являлся Д Небаба
Герцен время ссылки января года назначен главным редактором автором неофициальной части полном собрании сочинений помещены газетных статей Благодаря Герцену газете опубликовано большое количество материалов документов истории Владимирской губернии включая различные очерки Владимире Суздале Шуе также описания древнейших памятников зодчества трактат развитии промышленности Вязниках другое
середины года главным помощником Герцена неофициальной части становится Е Протопопов после возвращения первого ссылки годах становится главным редактором Протопопове неофициальная часть газеты стала углублённо заниматься краеведением превратилась центр местных краеведов Краевед Смирнова отмечал Борисов Доброхотов Н Тихонравов др должны признаны учениками Протопопов период годы написал общей сложности около статей газету
годах главным редактором неофициальной части Способин годах М Кротков годах Доброхотов апреля года Н Тихонравов году начиная П Проскура году начиная Н Артлебен году начиная Альбицкий
Тихонравов сумел добиться газета стала лучших периодических изданий широте охвата опубликованных археологических этнографических исследований материалов ранее неизданных исторических документов Тихомирову принадлежит около материалов опубликованных Ведомостях получил прозвище владимирского Несторалетописца
Тихонравов создал новые отделы городских известий вестей провинции также сеть собственных корреспондентов уездах способствовало превращению газеты издание насыщенное местной тематикой Кроме смог увеличить тираж издания экземпляров число частных подписчиков довести человек М Н Мазаев Энциклопедическом словаре Брокгауза Ефрона отмечал время главными редакторами Тихонравов Артлебен требование газету увеличилось экз
Известными сотрудниками газеты являлись Борисов Веселовский П Гаврилов иеромонах Иоасаф Гапонов Голышев П Гундобин Д Дмитревский М Лядов Н Шаганов году газете работал М Е СалтыковЩедрин
Газета закрыта году
Правопреемником Владимирских губернских ведомостей считает созданная году газета Владимирские ведомости
общество стало учредителей журнала Биология внутренних вод
Органом управления Гидробиологического Общества период между съездами является Центральный совет Общества входят Президиум Центрального совета председатели региональных отделений Общества Президент Президиум Центрального совета ГБО РАН Голубков Сергей Михайлович членкорреспондент РАН Зоологический институт РАН
Президентами общества
Систематикав Викивидах
Поиск изображенийна Викискладе
лат вид полужесткокрылых насекомыхкокцид рода семейства мучнистые червецы
Африка Египет Азия Иордания
Питаются соками корней растений
Вид впервые описан году энтомологом Дж Холлом
Таксон включён состав рода Видовое название происходит родового имени растенияхозяина происходит развитие червецов
Е Чжэюнь китайский бизнесмен обвинён причастности коррупции бельгийском футболе скандалу со ставками году Несколько команд иили игроков получили деньги влияние результаты матчей вовлечённые игроки уверены возможности получения прибыли
Команды фигурировали скандале Льерс ЛаЛувьер СентТрюйден Монс Вербрудеринг Гел Беерсхот Е Чжэюнь всегда подбирал команды финансовыми проблемами исключением Беерсхота время должен провести решающий матч против боровшегося выживание Монса Слухи договорных играх начали ходить после нескольких матчей очень много ставок необычными событиями иили результатами например Льерс дважды неожиданно выйдет матч резервным составом Е Чжэюнь также владельцем финской команды Алианси ныне существующего обанкротившегося клуба также повидимому конце существования также участником договорных матчей Полиция расследовала дело нашла достаточных доказательств
Королевская бельгийская футбольная ассоциация подверглась жёсткой критике со стороны прессы футбольных болельщиков ненадлежащее расследование данного случая Много игроков команд обвинены причастности коррупции конце концов договорных матчах признаны виновными команда Льерс переведён третий дивизион тренер Паул Пут трёхлетняя дисквалификация игрок Хасан Качич двухлетняя дисквалификация Льерс Качич обжаловали приговор конечном итоге марта оправданы
Е Чжэюнь основном работал вместе Пьетро Аллаттой Оливье Сураем Полиция арестовала обоих освобождены после допроса марта Министерство юстиции Бельгии выдало международный ордер арест Е Чжэюня данный момент место пребывания неизвестно адвокат сказал интервью французский спортивной газете Е Чжэюнь отрицал обвинения время находился гдето Китае
августа года федеральный прокурор объявил хочет расследовать дело установлено бывший тренер Льерс Паул Пут вратарь Клифф Мардулье восемь других эксигроков Льерса получили взятки между евро человека
лат подсемейство двукрылых семейства жужжал
Афротропика южная Палеарктика
представители подсемейства коренастые компактные мухи часто пчелоподобные внешнему виду обычно встречаются отдыхающими цветах особенно маргаритках семейства Отдельные особи обычно покрываются пыльцевыми зернами запутываются волосах Синапоморфии таксона педицель небольшим дорсальным шипом задний край эпандрия со сложной выемкой также встречается Жгутик усика щупики одночлениковые Крылья тремя ветвями жилки М присутствует анальная ячейка обычно закрыта Пропрестернум грушевидный анепимерон голый латеротергит медиотергит голые Преанальные щетинки отсутствуют исключением нескольких присутствующих
Около родов Ранее группу рассматривали трибу подсемействе года статусе отдельного подсемейства
Население переписи года составляло человека Почтовый индекс Телефонный код Занимает площадь км Код КОАТУУ
Одесская обл Великомихайловский рн Полезное ул Набережная
Князь Даниил Иванович Долгоруков воевода окольничий Смутное время времена правления царя Михаила Фёдоровича Рюрикович колене
Сын князя Ивана Андреевича ДолгоруковаШибана Имел брата князя Фёдора Ивановича
Воевода послан князем Мстиславским войском Путивлю против поляков апреля Назначен м воеводой Тверь челобитью Тверич князь Данилу Твери велено Назначен размене пленных переназначено отправиться Калугу декабрь Встречал санях английского посла декабря Первый воевода Калуге декабре велено идти Брянск оттуда идти литовских людей воинским людям собираться Калуге Первый воевода Калуге должен очистить Рославльский уезд поляков пошёл Дорогобужу поляки отошли Смоленску велено обождать после отозван Москву Присутствовал й встрече персидского посла ноября отпуске января поводу родственник Г ДолгорукийЧертёнок местничал просил записать ровень случай осады Москвы королевичем Владиславом должен защищать Калужские ворота сентябрь Пожалован окольничии декабря Послан размена пленными крымцами Исполнял дворцовые службы встречал провожал послов часто приглашаем Государеву столу свадьбе царя царицы конюшево место ходил санями сентября Обедал Государя декабря местничество Фёдором Ивановичем Шереметьевым посажен тюрьму послан князь Данила тюрьму сидел дня праздник Рождества Христово Государь пожаловал тюрьмы выпустить велел со двора съезжать велено Государева указу второй свадьбе Государя распоряжался поезжанами царицыных саней февраля Послан Валуйки размена пленных где скончался
Владел поместьями вотчинами Московском уезде
Лжедмитрии окольничим вступлении престол царя Михаила Фёдоровича видимо писался Посылал карего бобра бил челом Петру Сапеге где называл окольничим Государя Дмитрия Ивановича
Год смерти князя Даниила Ивановича П Долгорукова Русском биографическом словаре означен деле умер конце июля начале августа явствует донесения дьяка Ивана Михайловича подтверждается приёме шведского посла парада ноября жена выставляла людей
Жена Мария Алексеевна свадьбе Государя й свахой Государевой стороны имела поместья Малоярославецком уезде
основе спектакля году Творческим объединением Экран снят одноимённый телевизионный художественный фильм
роли Карлсона Спартак Мишулин октября июля выступил театральной сцене более двух тысяч раз объехав спектаклем страну Актёр играл роль Театре сатиры более тридцати пяти лет
Озорной Карлсон доверчивый Малыш герои известной сказки Карлсон красивый умный меру упитанный мужчина расцвете сил живёт крыше умеет летать очень любит пошалить последствия шалостей фирменная отговорка Пустяки делото житейское Правда родители Малыша считают равно скучать со летающим другом приходится лазая крышам друзья предотвращают крупную кражу роли квартирного вора Андрей Миронов вместе укрощают злую домомучительницу фрекен Бок
возвращении школы Малыш находит потерянного пуделя поводком решает завести дома Однако хозяйка находит пуделя увозит машине Малыш подумал жизнь проживёт без собаки

In [30]:
import os

directory_path = '.\data\wiki'

# Перебираем все файлы в директории
for filename in os.listdir(directory_path):
    filepath = os.path.join(directory_path, filename)

    # Проверяем, является ли объект по указанному пути файлом
    if os.path.isfile(filepath):
        print(filepath)

.\data\wiki\random_pages10.txt
.\data\wiki\random_pages11.txt
.\data\wiki\random_pages12.txt
.\data\wiki\random_pages13.txt
.\data\wiki\random_pages14.txt
.\data\wiki\random_pages15.txt
.\data\wiki\random_pages16.txt
.\data\wiki\random_pages17.txt

In [31]:
import os

directory_path = '.\data\wiki'

all_wiki_lines = []
for filename in os.listdir(directory_path):
    filepath = os.path.join(directory_path, filename)

    # Проверяем, является ли объект по указанному пути файлом
    if os.path.isfile(filepath):
        print(filepath)
        processed_lines = preprocess_file(filepath)
        all_wiki_lines += processed_lines

.\data\wiki\random_pages10.txt
.\data\wiki\random_pages11.txt
.\data\wiki\random_pages12.txt
.\data\wiki\random_pages13.txt
.\data\wiki\random_pages14.txt
.\data\wiki\random_pages15.txt
.\data\wiki\random_pages16.txt
.\data\wiki\random_pages17.txt

In [32]:
wiki_df = pd.DataFrame(all_wiki_lines, columns=['text'])

wiki_df['is_noisy_text'] = False

wiki_df

                                                   text  is_noisy_text
0     Торремолинос исп город муниципалитет Испании в...        False
1         Занимает площадь км Население тыс человек год        False
2      Расстояние административного центра провинции км        False
3     Пляжный курорт средиземноморском побережье Исп...        False
4     Рогатица босн серб Рогатица хорв город восточн...        False
...                                                 ...          ...
6427  Сибинович являлся членом Ассоциации литературн...        False
6428  сентября года знак протеста против нового Зако...        False
6429  Сибинович награждён Премией достижения области...        False
6430  шведская независимая звукозаписывающая компани...        False
6431  основан Бенгтом Рамом году Мальмё образцу нише...        False

[6432 rows x 2 columns]

In [33]:
wiki_df.to_csv('./data/wiki_df.csv', index=False)

In [34]:
filtered_df = wiki_df.loc[wiki_df['text'].str.len() >= 30]
filtered_df

                                                   text  is_noisy_text
0     Торремолинос исп город муниципалитет Испании в...        False
1         Занимает площадь км Население тыс человек год        False
2      Расстояние административного центра провинции км        False
3     Пляжный курорт средиземноморском побережье Исп...        False
4     Рогатица босн серб Рогатица хорв город восточн...        False
...                                                 ...          ...
6427  Сибинович являлся членом Ассоциации литературн...        False
6428  сентября года знак протеста против нового Зако...        False
6429  Сибинович награждён Премией достижения области...        False
6430  шведская независимая звукозаписывающая компани...        False
6431  основан Бенгтом Рамом году Мальмё образцу нише...        False

[5550 rows x 2 columns]

In [35]:
filtered_df.to_csv('./data/filtered_wiki_df.csv', index=False)

In [36]:
filtered_df['text'].tail()

6427    Сибинович являлся членом Ассоциации литературн...
6428    сентября года знак протеста против нового Зако...
6429    Сибинович награждён Премией достижения области...
6430    шведская независимая звукозаписывающая компани...
6431    основан Бенгтом Рамом году Мальмё образцу нише...
Name: text, dtype: object